### ISSUE TITLE
Add instagram to footer

### ISSUE THREAD

**Issue by calvinatian** [BUGS-NYU/bugs-nyu.github.io#120]
![image](https://github.com/BUGS-NYU/bugs-nyu.github.io/assets/48587962/1eb46906-b8f9-4837-9054-45905b546539)

**Comment by PraveenShinde3** [comment]
@calvinatian Can you please assign it to me?

Query :  Do I need to add a link or just the icon?

**Comment by calvinatian** [comment]
> @calvinatian Can you please assign it to me?
> 
> Query : Do I need to add a link or just the icon?

@PraveenShinde3 Try to follow the existing format: an icon that links to the instagram when clicked

**Comment by PraveenShinde3** [comment]
@calvinatian can i get the Instagram link which needs to be linked?

**Comment by PraveenShinde3** [comment]
![image](https://github.com/BUGS-NYU/bugs-nyu.github.io/assets/107350270/8c02c9e3-f33c-42db-995b-342c316155e4)

I have added the Instagram link and followed the same pattern as used for other icons. Below is the updated code. I just need your Instagram link so that I update that and create a Pull Request for it.

Code
```{ to: 'https://www.instagram.com/', getMark: () => <Instagram /> },```

**Comment by calvinatian** [comment]
~~https://www.instagram.com/nyubugs/~~
https://www.instagram.com/bugsnyu/

**Comment by PraveenShinde3** [comment]
Thanks, will update this link and create a PR
